apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::888682136042:role/eksctl-spot-cluster-nodegroup-spot-NodeInstanceRole-L4Tp9DON0xhh
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - usearn: arn:aws:iam::888682136042:user/roboshop-admin
      username: roboshop-admin
kind: ConfigMap
metadata:
  creationTimestamp: "2024-03-04T09:09:55Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2677"
  uid: 5a26f92c-22b0-4c2f-a45b-dc3cb9ae33b9

