apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::888682136042:role/eksctl-spot-cluster-nodegroup-spot-NodeInstanceRole-U0rpxYecq2rC
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - usearn: arn:aws:iam::888682136042:user/roboshop-admin
      username: roboshop-admin
kind: ConfigMap
metadata:
  creationTimestamp: "2024-02-29T03:09:53Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1213"
  uid: 0d40ee98-6269-48be-a1da-fb0ce9f515ee
