apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::752692907119:role/eksctl-eks-cluster-nodegroup-spot-NodeInstanceRole-4T0W6O7D3TWQ
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::752692907119:user/roboshop-admin
      username: roboshop-admin
kind: ConfigMap
metadata:
  creationTimestamp: "2023-04-06T14:21:32Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1574"
  uid: 8f315a3c-0937-46b6-bc0d-d401c219352b